title = "gitleaks config"
[[rules]]
    description = '''ADMIN_PASSWORD'''
    regex = '''(admin).+(secret|token|key|password).+'''
    tags = ["secret"]

[[rules]]
    description = '''AWS API Gateway'''
    regex = '''[0-9a-z]+.execute-api.[0-9a-z.-_]+.amazonaws.com'''
    tags = ["secret"]

[[rules]]
    description = '''AWS API Key'''
    regex = '''AKIA[0-9A-Z]{16}'''
    tags = ["secret"]

[[rules]]
    description = '''AWS ARN'''
    regex = '''arn:aws:[a-z0-9-]+:[a-z]{2}-[a-z]+-[0-9]+:[0-9]+:.+'''
    tags = ["secret"]
