# Example GitLeaks configuration file

# List of rules to apply during the scan
[[rules]]
  description = "AWS Access Key"
  regex = '''(?i)AKIA[0-9A-Z]{16}'''

[[rules]]
  description = "Google API Key"
  regex = '''(?i)AIza[0-9A-Za-z\\-_]{35}'''

[[rules]]
  description = "Private Key"
  regex = '''-----BEGIN (RSA|DSA|EC|OPENSSH) PRIVATE KEY-----'''

# File extensions to include or exclude from the scan
[files]
  include = [
    "**/*.txt",
    "**/*.md",
    "**/*.config",
    "**/*.yml",
    "**/*.yaml"
  ]

  exclude = [
    "**/*.html",
    "**/*.css"
  ]

# Other GitLeaks configuration options
[options]
  # Number of concurrent goroutines to use during the scan
  threads = 10

  # Whether to scan commit history or just the latest commit
  all-branches = false

  # Whether to scan submodules recursively
  scan-submodules = false