title = "gitleaks config"
[[rules]]
    description = '''ADMIN_PASSWORD'''
    id = "admin-passwor"
    regex = '''(admin).+(secret|token|key|password).+'''
    tags = ["secret"]

[[rules]]
    description = '''AWS API Gateway'''
    id = "aws-api-gateway"
    regex = '''[0-9a-z]+.execute-api.[0-9a-z.-_]+.amazonaws.com'''
    tags = ["secret"]

[[rules]]
    description = '''AWS API Key'''
    id = "aws-api-key"
    regex = '''AKIA[0-9A-Z]{16}'''
    tags = ["secret"]

[[rules]]
    description = '''AWS ARN'''
    id = "aws-arm"
    regex = '''arn:aws:[a-z0-9-]+:[a-z]{2}-[a-z]+-[0-9]+:[0-9]+:.+'''
    tags = ["secret"]

[[rules]]
    description = '''AWS Access Key ID Value'''
    regex = '''(A3T[A-Z0-9]|AKIA|AGPA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'''
    tags = ["secret"]

[[rules]]
    description = '''AWS AppSync GraphQL Key'''
    regex = '''da2-[a-z0-9]{26}'''
    tags = ["secret"]

[[rules]]
    description = '''AWS MWS key'''
    regex = '''amzn\.mws\.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'''
    tags = ["secret"]

[[rules]]
    description = '''AWS RDS'''
    regex = '''[0-9a-z.-_]+.rds.amazonaws.com'''
    tags = ["secret"]

[[rules]]
    description = '''AWS S3 Bucket'''
    regex = '''s3://[0-9a-z.-_/]+'''
    tags = ["secret"]

[[rules]]
    description = '''AWS S3 Endpoint'''
    regex = '''[a-zA-Z0-9.-_]+.s3.[a-zA-Z0-9.-_]+.amazonaws.com'''
    tags = ["secret"]

[[rules]]
    description = '''AWS client ID'''
    regex = '''(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'''
    tags = ["secret"]

[[rules]]
    description = '''AWS cred file info'''
    regex = '''(aws_access_key_id|aws_secret_access_key)'''
    tags = ["secret"]
