title = "gitleaks config"
[[rules]]
    description = '''ADMIN_PASSWORD'''
    id = "ADMIN_PASSWORD"
    regex = '''(admin).+(secret|token|key|password).+'''
    tags = ["secret"]

[[rules]]
    description = "Discovered a Hugging Face Access token, which could lead to unauthorized access to AI models and sensitive data."
    id = "huggingface-access-token"
    regex = '''(?:^|[\\'"` >=:])(hf_[a-zA-Z]{34})(?:$|[\\'"` <])'''
    entropy = 1
    keywords = [
        "hf_",
    ]
    tags = ["secret"]

[[rules]]
    description = "Uncovered a Hugging Face Organization API token, potentially compromising AI organization accounts and associated data."
    id = "huggingface-organization-api-token"
    regex = '''(?:^|[\\'"` >=:\(,)])(api_org_[a-zA-Z]{34})(?:$|[\\'"` <\),])'''
    entropy = 2
    keywords = [
        "api_org_",
    ]
    tags = ["secret"]

[[rules]]
    description = '''Unplugg'''
    id = "Unplugg"
    regex = '''(?:unplu).{0,40}\b([a-z0-9]{64})\b'''
    tags = ["secret"]


[[rules]]
    description = "OpenAI API Key"
    id = "openai-api-key"
    regex = '''(?i)\b(sk-[a-zA-Z0-9]{20}T3BlbkFJ[a-zA-Z0-9]{20})(?:['|\"|\n|\r|\s|\x60|;]|$)'''
    secretGroup = 1
    tags = ["openapi"]
	
[allowlist]
description = "ignore commits"
commits = ["4c7f9c7d0add250a4bcf196a95ff5f64864c9312"]
paths = [
  '''modules/domino_EKS/examples/examples.pem'''
]
