name: GitLeaks

on:
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
          
      - name: Install GitLeaks
        run: go install github.com/zricethezav/gitleaks/v8@latest

      - name: Run GitLeaks
        run: gitleaks --config-path= /github/.gitleaks.toml
      
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}
