name: apply

on:
  push:
    branches:
      - 'main'
  release:
    types: ["published"]



jobs:
  apply:
    name: apply
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v4
        
      - name: terraform plan
        run: |
          terraform plan
        shell: bash

      - name: Approval
        id: approval
        run: |
          echo "Do you approve the deployment? (yes/no)"
          read approval
          echo "::set-output name=approval::$approval"
        shell: bash

      - name: terraform apply
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && steps.approval.outputs.approval == 'yes' }}
        run: |
          terraform apply
        shell: bash
